/*
    ChibiOS - Copyright (C) 2006-2026 Giovanni Di Sirio.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/**
 * @file    RP2350/hal_lld.c
 * @brief   RP2350 HAL subsystem low level driver source.
 * @note    The Core 1 launch sequence follows the multicore launch protocol
 *          documented in RP2350 Datasheet 3.5 "Multicore Launch".
 *
 * @addtogroup HAL
 * @{
 */

#include "hal.h"
#include "rp_clocks.h"

/*===========================================================================*/
/* Driver local definitions.                                                 */
/*===========================================================================*/

/*===========================================================================*/
/* Driver exported variables.                                                */
/*===========================================================================*/

/**
 * @brief   CMSIS system core clock variable.
 * @note    It is declared in system_rp2350.h.
 */
uint32_t SystemCoreClock = RP_CLK_SYS_FREQ;

/*===========================================================================*/
/* Driver local variables and types.                                         */
/*===========================================================================*/

/*===========================================================================*/
/* Driver local functions.                                                   */
/*===========================================================================*/

#if RP_CORE1_START == TRUE
/*
 * Debug-visible core1 startup markers.
 *
 * These are intentionally non-static so SWD/GDB can inspect them during
 * early boot deadlock diagnosis without requiring a console.
 */
volatile uint32_t rp2350_c1_boot_stage;
volatile uint32_t rp2350_c1_startup_result;

static bool fifo_read_timeout(uint32_t *value, uint32_t wait_cycles) {
  while (wait_cycles-- > 0U) {
    if (fifoIsReadNotEmpty()) {
      *value = SIO->FIFO_RD;

      /* In case the other core is in WFE, signaling space available. */
      __SEV();
      return true;
    }

    /*
     * Use a bounded busy-wait so timeout always expires even if no event is
     * generated by the peer core.
     */
    __NOP();
  }

  return false;
}

static void start_core1(void) {
  extern uint32_t RP_CORE1_STACK_END;
  extern uint32_t RP_CORE1_VECTORS_TABLE;
  extern void RP_CORE1_ENTRY_POINT(void);
  static const uint32_t cmd_sequence[] = {0, 0, 1,
                             (uint32_t)&RP_CORE1_VECTORS_TABLE,
                             (uint32_t)&RP_CORE1_STACK_END,
                             (uint32_t)RP_CORE1_ENTRY_POINT};
  unsigned seq;
  uint32_t attempts;

  rp2350_c1_boot_stage = 1U;
  rp2350_c1_startup_result = 0U;

  /* Force-reset core1 via PSM before starting the FIFO launch handshake.
   *
   * If core1 survived a preceding soft reset (e.g. jump_to_app() in the
   * bootloader, which does a BX not SYSRESETREQ), it may still be executing
   * application code from a previous run.  In that case the ROM FIFO
   * handshake protocol will deadlock: core0 sends the sync sequence but
   * core1 is not in the ROM wait-for-launch loop so it never echoes back.
   *
   * PSM FRCE_OFF[24] holds core1 in reset (powered-off state).  Clearing
   * it releases core1 into the ROM boot-path which immediately enters the
   * wait-for-launch loop.  The PSM DONE bit falls while the core is held
   * off, and rises again once it has been released and is running. */
  PSM->FRCE_OFF = PSM_ANY_PROC1;              /* assert reset to core1  */
  while (PSM->DONE & PSM_ANY_PROC1) {}        /* wait until it powers off */
  PSM->FRCE_OFF = 0U;                         /* release — core1 enters ROM */
  rp2350_c1_boot_stage = 2U;

  /* Starting core 1.*/
  seq = 0;
  attempts = 0U;
  do {
    uint32_t response;
    uint32_t cmd = cmd_sequence[seq];

    /* Flushing the FIFO state before sending a zero.*/
    if (!cmd) {
      fifoFlushRead();
    }
    fifoBlockingWrite(cmd);

    /*
     * Guard the ROM echo wait with a timeout so startup cannot deadlock
     * indefinitely if core1 is not in the expected launch loop.
     */
    if (!fifo_read_timeout(&response, 500000U)) {
      rp2350_c1_boot_stage = 0xE0010000U | seq;
      rp2350_c1_startup_result = 1U;
      return;
    }

    /* Checking response, going forward or back to first step.*/
    seq = cmd == response ? seq + 1U : 0U;
    attempts++;
    if (attempts > 128U) {
      rp2350_c1_boot_stage = 0xE0020000U | seq;
      rp2350_c1_startup_result = 2U;
      return;
    }
  } while (seq < 6U);

  rp2350_c1_boot_stage = 3U;
  rp2350_c1_startup_result = 0xC0010000U;
}
#endif

/*===========================================================================*/
/* Driver interrupt handlers.                                                */
/*===========================================================================*/

/*===========================================================================*/
/* Driver exported functions.                                                */
/*===========================================================================*/

/**
 * @brief   Low level HAL driver initialization.
 *
 * @notapi
 */
void hal_lld_init(void) {

#if RP_NO_INIT == FALSE
  rp_clock_init();

  hal_lld_peripheral_unreset(RESETS_ALLREG_BUSCTRL);
  hal_lld_peripheral_unreset(RESETS_ALLREG_SYSINFO);
  hal_lld_peripheral_unreset(RESETS_ALLREG_SYSCFG);
#endif /* RP_NO_INIT */

  /* NVIC initialization.*/
  nvicInit();

  /* IRQ subsystem initialization.*/
  irqInit();
#if defined(RP_DMA_REQUIRED)
  dmaInit();
#endif
#if defined(RP_PIO_REQUIRED)
  pioInit();
#endif

  /* Bind the system timer IRQ to this core for tickless mode. */
#if OSAL_ST_MODE == OSAL_ST_MODE_FREERUNNING
  stBind();
#endif

#if RP_CORE1_START == TRUE
  start_core1();
#endif
}

/** @} */
